include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    invalid_annotation_target: ignore
  plugins:
    - dart_code_metrics
    - linter

linter:
  rules:
    - annotate_overrides
    - hash_and_equals
    - prefer_is_not_empty

dart_code_metrics:
  anti-patterns:
    - long-method
    - long-parameter-list
  metrics:
    cyclomatic-complexity: 10
    maximum-nesting-level: 5
    number-of-parameters: 6
    source-lines-of-code: 120
    technical-debt:
      threshold: 1
      todo-cost: 161
      ignore-cost: 320
      ignore-for-file-cost: 396
      as-dynamic-cost: 322
      deprecated-annotations-cost: 37
      file-nullsafety-migration-cost: 41
      unit-type: "TRY"
  metrics-exclude:
    - test/**
  rules:
    - member-ordering:
        alphabetize: true
        order:
          - public-fields
          - private-fields
          - constructors
          - public-methods
          - private-methods
    - newline-before-return
    - no-boolean-literal-compare
    - no-empty-block
    - prefer-trailing-comma
    - prefer-conditional-expressions
    - no-equal-then-else
    - always-remove-listener
    - avoid-unnecessary-setstate
    - prefer-const-border-radius
    - avoid-non-null-assertion
    - prefer-async-await
    - prefer-first
    - prefer-last
    - prefer_single_quotes
