name: analytic_error_example
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: 3.0.5

dependencies:
  flutter:
    sdk: flutter

  #Firebase
  firebase_analytics: 9.3.3
  firebase_core: 1.21.1
  firebase_crashlytics: 2.8.9
  firebase_performance: 0.8.2+4

  #UI
  cupertino_icons: 1.0.5
  google_fonts: 3.0.1

  #Linter
  dart_code_metrics: 4.17.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  #Linter
  flutter_lints: 2.0.1

flutter:
  uses-material-design: true
